apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
  namespace: chat-dev
  labels:
    app: frontend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mdarifahammedreza/simpleChatui-frontend:dev-latest
          ports:
            - containerPort: 5173
          env:
            - name: NODE_ENV
              value: "development"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
