apiVersion: v1
kind: Service
metadata:
  name: frontend-prod
  namespace: chat-prod
  labels:
    app: frontend
    env: prod
spec:
  type: ClusterIP
  selector:
    app: frontend
    env: prod
  ports:
    - port: 80
      targetPort: 80
