apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-stage
  namespace: chat-stage
  labels:
    app: frontend
    env: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      env: stage
  template:
    metadata:
      labels:
        app: frontend
        env: stage
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mdarifahammedreza/simpleChatui-frontend:stage-latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
