apiVersion: v1
kind: Service
metadata:
  name: frontend-stage
  namespace: chat-stage
  labels:
    app: frontend
    env: stage
spec:
  type: ClusterIP
  selector:
    app: frontend
    env: stage
  ports:
    - port: 80
      targetPort: 80
